# Generated by Django 5.2.13 on 2026-08-15 11:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquahomeapp', '0002_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_vn', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('min_temp', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('min_ph', models.FloatField()),
                ('max_ph', models.FloatField()),
                ('max_length', models.FloatField()),
                ('min_tank_size', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='aquahomeapp.species'),
        ),
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, max_length=1000)),
                ('priority', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_recommendations', to='aquahomeapp.product')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='aquahomeapp.species')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('species', 'product'), name='unique_species_product_recommendation')],
            },
        ),
    ]
